# Generated by Django 4.2.23 on 2025-09-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节名')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('format', models.CharField(max_length=50, verbose_name='章节风格')),
                ('video_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频路径')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.CharField(max_length=20, verbose_name='分镜序号')),
                ('featured_character', models.CharField(max_length=100, verbose_name='特写人物')),
                ('narration', models.TextField(verbose_name='解说内容')),
                ('image_prompt', models.TextField(verbose_name='图片prompt')),
                ('narration_mp3_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='解说mp3路径')),
                ('tts_response', models.TextField(blank=True, null=True, verbose_name='tts response')),
                ('subtitle_content', models.TextField(blank=True, null=True, verbose_name='字幕文件内容')),
                ('narration_mp4_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='解说mp4路径')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrations', to='video.chapter', verbose_name='对应章节')),
            ],
            options={
                'verbose_name': '解说',
                'verbose_name_plural': '解说',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=10, verbose_name='性别')),
                ('age_group', models.CharField(choices=[('儿童', '儿童'), ('青少年', '青少年'), ('青年', '青年'), ('中年', '中年'), ('老年', '老年')], max_length=20, verbose_name='年龄段')),
                ('hair_style', models.CharField(blank=True, max_length=100, null=True, verbose_name='发型')),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='发色')),
                ('face_features', models.TextField(blank=True, null=True, verbose_name='面部特征')),
                ('body_features', models.TextField(blank=True, null=True, verbose_name='身材特征')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='特殊标记')),
                ('chapters', models.ManyToManyField(related_name='characters', to='video.chapter', verbose_name='对应章节')),
            ],
            options={
                'verbose_name': '出镜人物',
                'verbose_name_plural': '出镜人物',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='video.novel', verbose_name='对应小说'),
        ),
    ]
