# Generated by Django 4.2.23 on 2025-09-04 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='小说内容'),
        ),
        migrations.AddField(
            model_name='novel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AddField(
            model_name='novel',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='novels/', verbose_name='原始文件'),
        ),
        migrations.AddField(
            model_name='novel',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
    ]
