# Generated by Django 4.2.23 on 2025-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_novel_content_novel_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型'),
        ),
    ]
