# Generated by Django 4.2.23 on 2025-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_novel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当前任务ID'),
        ),
        migrations.AddField(
            model_name='novel',
            name='task_message',
            field=models.TextField(blank=True, null=True, verbose_name='任务消息'),
        ),
        migrations.AddField(
            model_name='novel',
            name='task_status',
            field=models.CharField(choices=[('idle', '空闲'), ('generating_script', '生成解说文案中'), ('script_completed', '解说文案已完成'), ('script_failed', '解说文案生成失败'), ('validating_script', '校验解说文案中'), ('validation_completed', '解说文案校验完成'), ('validation_failed', '解说文案校验失败')], default='idle', max_length=50, verbose_name='任务状态'),
        ),
        migrations.AddField(
            model_name='novel',
            name='task_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='任务状态更新时间'),
        ),
    ]
