# Generated by Django 4.2.23 on 2025-09-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_novel_current_task_id_novel_task_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImageTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('image_style', models.CharField(choices=[('realistic', '写实风格'), ('anime', '动漫风格'), ('cartoon', '卡通风格'), ('oil_painting', '油画风格')], default='realistic', max_length=20, verbose_name='图片风格')),
                ('image_quality', models.CharField(choices=[('standard', '标准'), ('hd', '高清'), ('ultra', '超高清')], default='standard', max_length=20, verbose_name='图片质量')),
                ('image_count', models.IntegerField(default=1, verbose_name='生成数量')),
                ('custom_prompt', models.TextField(blank=True, null=True, verbose_name='自定义提示词')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='日志信息')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('generated_images', models.JSONField(blank=True, default=list, verbose_name='生成的图片路径列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_image_tasks', to='video.chapter', verbose_name='章节')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tasks', to='video.character', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色图片生成任务',
                'verbose_name_plural': '角色图片生成任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
