# Generated by Django 4.2.23 on 2025-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_characterimagetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='角色图片路径'),
        ),
    ]
