# Generated by Django 4.2.23 on 2025-09-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_character_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='chapters',
        ),
        migrations.AddField(
            model_name='character',
            name='chapter',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='video.chapter', verbose_name='对应章节'),
            preserve_default=False,
        ),
    ]
