# Generated by Django 4.2.23 on 2025-09-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_character_chapters_character_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGenerationTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='日志信息')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('total_segments', models.IntegerField(default=0, verbose_name='总段数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功生成数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('generated_audio_files', models.JSONField(blank=True, default=list, verbose_name='生成的音频文件路径列表')),
                ('generated_timestamp_files', models.JSONField(blank=True, default=list, verbose_name='生成的时间戳文件路径列表')),
                ('generated_ass_files', models.JSONField(blank=True, default=list, verbose_name='生成的ASS字幕文件路径列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tasks', to='video.chapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '音频生成任务',
                'verbose_name_plural': '音频生成任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
