# Generated by Django 5.2.6 on 2025-09-11 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_audiogenerationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Celery任务ID'),
        ),
        migrations.AddField(
            model_name='narration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narration',
            name='generated_images',
            field=models.JSONField(blank=True, default=list, verbose_name='生成的图片路径列表'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='图片任务完成时间'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_error',
            field=models.TextField(blank=True, null=True, verbose_name='图片任务错误信息'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_message',
            field=models.TextField(blank=True, null=True, verbose_name='图片任务日志信息'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_progress',
            field=models.IntegerField(default=0, verbose_name='图片任务进度百分比'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='图片任务开始时间'),
        ),
        migrations.AddField(
            model_name='narration',
            name='image_task_status',
            field=models.CharField(choices=[('idle', '空闲'), ('pending', '等待中'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='idle', max_length=20, verbose_name='图片任务状态'),
        ),
        migrations.AddField(
            model_name='narration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='narration',
            name='volcengine_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='火山引擎任务ID'),
        ),
    ]
