# Generated by Django 4.2.23 on 2025-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_narration_celery_task_id_narration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='batch_image_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批量图片生成完成时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_error',
            field=models.TextField(blank=True, null=True, verbose_name='批量图片生成错误信息'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_message',
            field=models.TextField(blank=True, null=True, verbose_name='批量图片生成日志信息'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_progress',
            field=models.IntegerField(default=0, verbose_name='批量图片生成进度百分比'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批量图片生成开始时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_status',
            field=models.CharField(choices=[('idle', '空闲'), ('pending', '等待中'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='idle', max_length=20, verbose_name='批量图片生成状态'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='batch_image_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='批量图片生成任务ID'),
        ),
    ]
