# Generated by Django 4.2.23 on 2025-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_chapter_batch_image_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_count',
            field=models.IntegerField(default=0, verbose_name='旁白数量'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='image_count',
            field=models.IntegerField(default=0, verbose_name='图片数量'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='script_count',
            field=models.IntegerField(default=0, verbose_name='脚本数量'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subtitle_count',
            field=models.IntegerField(default=0, verbose_name='字幕数量'),
        ),
    ]
