# Generated by Django 4.2.23 on 2025-11-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_chapter_audio_count_chapter_image_count_and_more'),
    ]

    operations = [
    ]
