# Generated by Django 4.2.23 on 2025-11-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0012_add_chapter_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='review_reason',
            field=models.TextField(blank=True, null=True, verbose_name='审核失败原因'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='review_status',
            field=models.CharField(choices=[('pending', '未审核'), ('approved', '审核通过'), ('rejected', '审核失败')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chapters', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
