# Generated by Django 4.2.23 on 2025-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_chapter_review_reason_chapter_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='review_status',
            field=models.CharField(choices=[('not_submitted', '未审核'), ('reviewing', '审核中'), ('approved', '审核通过'), ('rejected', '审核失败')], default='not_submitted', max_length=20, verbose_name='审核状态'),
        ),
    ]
